version: '3.8'

services:

  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 3s
      timeout: 3s
      retries: 15
    ports:
      - "5432:5432"

volumes:
  pg_data:




